'reinit'
'open C:\njs\mk\mk.ctl'
'set grid off'
'set grads off'
'set t 1 30'
'set vrange -3.5 3.5'
'set xlopts 1 4 0.2'
'set ylopts 1 4 0.2'
'set cmark 0'
'd uf'
'set cmark 0'
'set cstyle 2'
'set ccolor 1'
'set cthick 6'
'd ub'
'set cmark 0'
'set ccolor 1'
'd a'
'set cmark 0'
'set ccolor 1'
'd b'
'printim C:\njs\mk\r.png white'
;